services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Scheduler\:
    resource: '../Classes/*'

  TYPO3\CMS\Scheduler\Command\SchedulerCommand:
    tags:
      - { name: 'console.command', command: 'scheduler:run', schedulable: false }
