services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\DependencyInjection\EnvVarProcessor:
    tags: ['container.env_var_processor']

  TYPO3\CMS\Core\Command\SiteListCommand:
    tags:
      - { name: 'console.command', command: 'site:list', schedulable: false }

  TYPO3\CMS\Core\Configuration\SiteConfiguration:
    arguments:
      $configPath: "%env(TYPO3:configPath)%/sites"

  TYPO3\CMS\Core\Package\PackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\FailsafePackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\UnitTestPackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Http\MiddlewareDispatcher:
    autoconfigure: false

  TYPO3\CMS\Core\Database\Schema\SqlReader:
    public: true

  # EventListeners
  TYPO3\CMS\Core\Compatibility\Slot\PostInitializeMailer:
    tags:
      - { name: event.listener,
          identifier: 'legacy-slot',
          event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent }
