services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\Configuration\SiteConfiguration:
    arguments:
      # @todo: this will create an absolute path
      # in the DI cache.
      # May need to be moved into a service provider.
      $configPath: "%path.config%/sites"

  TYPO3\CMS\Core\Package\PackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\FailsafePackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\UnitTestPackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Http\MiddlewareDispatcher:
    autoconfigure: false

  TYPO3\CMS\Core\Database\Schema\SqlReader:
    public: true
