services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\Package\PackageManager:
    autoconfigure: false
    tags:
      - { name: signal.slot, method: scanAvailablePackages, signalClass: 'PackageManagement', signalName: 'packagesMayHaveChanged' }

  TYPO3\CMS\Core\Resource\Security\StoragePermissionsAspect:
    tags:
      - { name: signal.slot, method: addUserPermissionsToStorage, signalClass: TYPO3\CMS\Core\Resource\ResourceStorage, signalName: 'postProcessStorage' }

  TYPO3\CMS\Core\Resource\Processing\FileDeletionAspect:
    tags:
      - { name: signal.slot, method: removeFromRepository, signalClass: TYPO3\CMS\Core\Resource\ResourceStorage, signalName: 'postFileDelete' }
      - { name: signal.slot, method: cleanupProcessedFilesPostFileAdd, signalClass: TYPO3\CMS\Core\Resource\ResourceStorage, signalName: 'postFileAdd' }
      - { name: signal.slot, method: cleanupProcessedFilesPostFileReplace, signalClass: TYPO3\CMS\Core\Resource\ResourceStorage, signalName: 'postFileReplace' }

  TYPO3\CMS\Core\Resource\OnlineMedia\Processing\PreviewProcessing:
    tags:
      - { name: signal.slot, method: processFile, signalClass: TYPO3\CMS\Core\Resource\ResourceStorage, signalName: 'preFileProcess' }


  TYPO3\CMS\Core\MetaTag\GenericMetaTagManager:
    tags:
      - { name: metatag.manager, identifier: generic, before: '' }
  TYPO3\CMS\Core\MetaTag\Html5MetaTagManager:
    tags:
      - { name: metatag.manager, identifier: html5 }
  TYPO3\CMS\Core\MetaTag\EdgeMetaTagManager:
    tags:
      - { name: metatag.manager, identifier: edge }
