services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Fluid\:
    resource: '../Classes/*'

  _instanceof:
    TYPO3\CMS\Extbase\Mvc\View\ViewInterface:
      shared: false
      public: true

  # Templateview has $context = null, symfony auto-injects in that case,
  # extbase did not, force passing `null`
  TYPO3\CMS\Fluid\View\TemplateView:
    arguments:
      $context: null

  TYPO3\CMS\Fluid\Core\Rendering\RenderingContext:
    arguments:
      $view: null


  TYPO3Fluid\Fluid\:
    resource: '%path.vendor%/typo3fluid/fluid/src/*'

  TYPO3Fluid\Fluid\View\TemplateView:
    arguments:
      $context: null

  # RenderingContext has __construct($view = null), symfony auto-injects in that case,
  # extbase did not, force passing `null`
  TYPO3Fluid\Fluid\Core\Rendering\RenderingContext:
    arguments:
      $view: null
