services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Redirects\:
    resource: '../Classes/*'

  TYPO3\CMS\Redirects\Controller\ManagementController:
    tags: ['backend.module_controller']

  TYPO3\CMS\Redirects\Service\RedirectService:
    arguments:
      $typolinkBuilderConfiguration: '%TYPO3_CONF_VARS.FE.typolinkBuilder%'
