services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  TYPO3\CMS\Redirects\Http\Middleware\RedirectHandler:
    arguments:
      - '@TYPO3\CMS\Redirects\Service\RedirectService'
    tags: ['typo3.middleware', 'psr.logger_aware']

  TYPO3\CMS\Redirects\Service\RedirectCacheService:
    arguments:
      - '@TYPO3\CMS\Core\Cache\CacheManager'

  TYPO3\CMS\Redirects\Service\RedirectService:
    arguments:
      - '@TYPO3\CMS\Redirects\Service\RedirectCacheService'
      - '@TYPO3\CMS\Core\LinkHandling\LinkService'
    tags: ['psr.logger_aware']

  TYPO3\CMS\Redirects\ViewHelpers\TargetPageIdViewHelper:
    tags: ['fluid.viewhelper']

  # Enable once these classes use depndency injection
  #TYPO3\CMS\Redirects\Controller\ManagementController:
  #  tags: ['backend.controller']
