services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  TYPO3\CMS\T3editor\Registry\AddonRegistry:
    tags: ['typo3.singleton']

  TYPO3\CMS\T3editor\Registry\ModeRegistry:
    tags: ['typo3.singleton']

  TYPO3\CMS\T3editor\T3editor:
    tags: ['typo3.singleton']
