services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\RteCKEditor\:
    resource: '../Classes/*'

  TYPO3\CMS\RteCKEditor\Form\Resolver\RichTextNodeResolver:
    public: true
