services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Lowlevel\:
    resource: '../Classes/*'

  TYPO3\CMS\Lowlevel\Controller\DatabaseIntegrityController:
    tags: ['backend.module_controller']

  TYPO3\CMS\Lowlevel\Controller\ConfigurationController:
    tags: ['backend.module_controller']
