services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Seo\:
    resource: '../Classes/*'

  TYPO3\CMS\Seo\MetaTag\OpenGraphMetaTagManager:
    tags:
      - { name: metatag.manager, identifier: opengraph }

  TYPO3\CMS\Seo\MetaTag\TwitterCardMetaTagManager:
    tags:
      - { name: metatag.manager, identifier: twitter }
