services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Form\:
    resource: '../Classes/*'
    exclude: '../Classes/{Controller,Domain/Model}'

  TYPO3\CMS\Form\Controller\:
    resource: '../Classes/Controller/*'
    public: true
