services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Backend\:
    resource: '../Classes/*'

  TYPO3\CMS\Backend\Template\ModuleTemplate:
    shared: false
    public: true

  TYPO3\CMS\Backend\Controller\PageLayoutController:
    tags: ['backend.module_controller']
  TYPO3\CMS\Backend\Controller\SiteConfigurationController:
    tags: ['backend.module_controller']
  TYPO3\CMS\Backend\Controller\HelpController:
    tags: ['backend.module_controller']

  TYPO3\CMS\Backend\Security\CategoryPermissionsAspect:
    tags:
      - { name: signal.slot, method: addUserPermissionsToCategoryTreeData, signalClass: TYPO3\CMS\Core\Tree\TableConfiguration\DatabaseTreeDataProvider, signalName: 'PostProcessTreeData' }
