services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Recordlist\:
    resource: '../Classes/*'

  TYPO3\CMS\Recordlist\Controller\RecordListController:
    tags: ['backend.module_controller']
