services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Tstemplate\:
    resource: '../Classes/*'

  TYPO3\CMS\Tstemplate\Controller\TypoScriptTemplateConstantEditorModuleFunctionController:
    tags: ['backend.controller']

  TYPO3\CMS\Tstemplate\Controller\TypoScriptTemplateModuleController:
    tags: ['backend.controller']

  TYPO3\CMS\Tstemplate\Controller\TypoScriptTemplateObjectBrowserModuleFunctionController:
    tags: ['backend.controller']
