services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Reports\:
    resource: '../Classes/*'

  TYPO3\CMS\Reports\Controller\ReportController:
    tags: ['backend.module_controller']
