services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Workspaces\:
    resource: '../Classes/*'

  TYPO3\CMS\Workspaces\Command\WorkspaceVersionRecordsCommand:
    tags:
      - { name: 'console.command', command: 'cleanup:versions' }

  TYPO3\CMS\Workspaces\Command\CleanupPreviewLinksCommand:
    tags:
      - { name: 'console.command', command: 'cleanup:previewlinks' }

  TYPO3\CMS\Workspaces\Command\AutoPublishCommand:
    tags:
      - { name: 'console.command', command: 'workspace:autopublish' }
